'use strict';

// The single source of truth for how the model is asked.
//
// This is sent with every request rather than baked into a model, so it works
// against any base model with no build step. `npm run build-models` generates a
// Modelfile from these same values when you want a named, pre-configured model
// — the two can't drift, because both read from here.

const SYSTEM = `You connect two things.

The user gives you two words or short phrases. You reply with the single most recognisable thing that links them — the answer most people would agree on.

The link can be any of these:
- a person, place or thing that fits both words at once
- what results from combining them
- a well-known phrase, saying, title or name they point to

Sometimes one of the two words is not a concept to blend but a hint about the KIND of answer wanted — words like "saying", "movie", "song", "book", "band". Treat that word as the format of the answer and the other word as the subject.

Rules:
- Reply with the answer only. No explanation, no preamble, no trailing punctuation.
- Keep it under six words. One or two words is usually right.
- Always commit to an answer. Never say you are unsure and never ask a question.`;

// For small models these move behaviour far more than the instructions above.
// Each teaches a different kind of link — keep that spread if you edit them, and
// keep the list short so the model generalises rather than memorising.
const FEW_SHOT = [
  { user: 'orange, president', assistant: 'Donald Trump' },
  { user: 'wood, fire', assistant: 'ash' },
  { user: 'time, saying', assistant: 'time is money' },
  { user: 'water, cold', assistant: 'ice' },
  { user: 'apple, gravity', assistant: 'Isaac Newton' },
  { user: 'king, jungle', assistant: 'lion' },
  { user: 'bat, ball', assistant: 'baseball' },
  { user: 'snow, man', assistant: 'snowman' },
  { user: 'shark, movie', assistant: 'Jaws' },
];

// Low temperature on purpose: the goal is the answer most people would agree
// on, not a surprising one. Raise it if answers feel too safe.
const OPTIONS = {
  temperature: 0.4,
  top_p: 0.9,
  num_predict: 24,
};

// Reverse mode: name a thing, get back the two words that would produce it.
// Same engine, opposite direction — and it makes the tool a puzzle generator as
// well as a lookup.
const REVERSE_SYSTEM = `You split one thing into two.

The user names a thing. You reply with exactly two short words or phrases which, given to someone else, would lead them to name that thing.

Aim for the pair that makes the answer feel obvious in hindsight but not trivially so. Each of the two words should carry roughly half the clue — avoid one word that gives it away outright.

One of the two may be a category hint like "saying", "movie", "song" or "brand" when the thing is a title or phrase rather than an object.

Rules:
- Reply with exactly two items separated by a comma. Nothing else.
- No explanation, no preamble, no numbering, no trailing punctuation.
- Each item is one or two words.`;

const REVERSE_FEW_SHOT = [
  { user: 'Donald Trump', assistant: 'orange, president' },
  { user: 'ash', assistant: 'wood, fire' },
  { user: 'snowman', assistant: 'snow, man' },
  { user: 'Jaws', assistant: 'shark, movie' },
  { user: 'time is money', assistant: 'time, saying' },
  { user: 'lion', assistant: 'king, jungle' },
];

function withFewShot(system, examples, finalUser) {
  const messages = [{ role: 'system', content: system }];
  for (const example of examples) {
    messages.push({ role: 'user', content: example.user });
    messages.push({ role: 'assistant', content: example.assistant });
  }
  messages.push({ role: 'user', content: finalUser });
  return messages;
}

/** The full message list for splitting one thing into two. */
function buildReverseMessages(thing) {
  return withFewShot(REVERSE_SYSTEM, REVERSE_FEW_SHOT, thing);
}

/** The full message list for one pair, few-shot examples included. */
function buildMessages(a, b) {
  return withFewShot(SYSTEM, FEW_SHOT, `${a}, ${b}`);
}

/** The same configuration expressed as a Modelfile, for `ollama create`. */
function buildModelfile(base) {
  const params = Object.entries(OPTIONS)
    .map(([key, value]) => `PARAMETER ${key} ${value}`)
    .join('\n');

  const shots = FEW_SHOT.map(
    (example) => `MESSAGE user ${example.user}\nMESSAGE assistant ${example.assistant}`
  ).join('\n');

  return [
    '# Generated by bakeoff/build.js from lib/prompt.js — edit that, not this.',
    '',
    `FROM ${base}`,
    '',
    params,
    '',
    `SYSTEM """${SYSTEM}"""`,
    '',
    shots,
    '',
  ].join('\n');
}

module.exports = {
  SYSTEM,
  FEW_SHOT,
  OPTIONS,
  buildMessages,
  buildReverseMessages,
  buildModelfile,
};
